# Generated by Django 5.2.15 on 2026-09-13 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0053_demo_guest_project_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DermatologyProject',
            fields=[
            ],
            options={
                'verbose_name': 'Dermatology project',
                'verbose_name_plural': 'Dermatology projects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.project',),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dermatology_folders_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dermatology.folder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dermatology_folders', to='common.project')),
            ],
            options={
                'db_table': 'dermatology_folder',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FolderAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('standard', 'Standard User'), ('annotator', 'Annotator'), ('project_manager', 'Project Manager')], default='standard', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_list', to='dermatology.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dermatology_folder_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dermatology_folderaccess',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('debug', 'Debug')], default='private', max_length=10)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='dermatology.folder')),
                ('modalities', models.ManyToManyField(blank=True, help_text='Modalities available for this patient', related_name='dermatology_patients', to='common.modality')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dermatology_patients', to='common.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dermatology_patients_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dermatology_patient',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('classifier', models.CharField(choices=[('manual', 'Manual'), ('pipeline', 'Pipeline')], default='manual', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('annotator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dermatology_classifications_authored', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='dermatology.patient')),
            ],
            options={
                'db_table': 'dermatology_classification',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QuadrantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#e74c3c', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dermatology_quadrant_types', to='common.project')),
            ],
            options={
                'db_table': 'dermatology_quadranttype',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuadrantClassificationMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_registry_id', models.IntegerField(blank=True, help_text='ID of the FileRegistry row (photo) this marker refers to', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dermatology_quadrant_markers', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadrant_markers', to='dermatology.patient')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_dermatology_quadrant_markers', to=settings.AUTH_USER_MODEL)),
                ('quadrant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='dermatology.quadranttype')),
            ],
            options={
                'db_table': 'dermatology_quadrantclassificationmarker',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuadrantTypeUserColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
                ('quadrant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_colors', to='dermatology.quadranttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dermatology_quadrant_colors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dermatology_quadranttypeusercolor',
            },
        ),
        migrations.CreateModel(
            name='RegionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#3498db', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dermatology_region_types', to='common.project')),
            ],
            options={
                'db_table': 'dermatology_regiontype',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RegionAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_registry_id', models.IntegerField(blank=True, help_text='ID of the FileRegistry row (photo) this annotation is drawn on', null=True)),
                ('tool', models.CharField(choices=[('brush', 'Brush'), ('eraser', 'Eraser'), ('polygon', 'Polygon')], max_length=20)),
                ('points', models.JSONField(default=list)),
                ('prompt_points', models.JSONField(blank=True, default=list)),
                ('stroke_width', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dermatology_annotations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_annotations', to='dermatology.patient')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_dermatology_annotations', to=settings.AUTH_USER_MODEL)),
                ('region_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='dermatology.regiontype')),
            ],
            options={
                'db_table': 'dermatology_regionannotation',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegionTypeUserColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
                ('region_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_colors', to='dermatology.regiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dermatology_region_colors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dermatology_regiontypeusercolor',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dermatology_tag',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='dermatology_name_ea706b_idx')],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='patients', to='dermatology.tag'),
        ),
        migrations.CreateModel(
            name='VoiceCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(help_text='Duration of audio recording in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modality', models.CharField(blank=True, default='', max_length=255)),
                ('text_caption', models.TextField(blank=True, null=True)),
                ('original_text_caption', models.TextField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edit_history', models.JSONField(blank=True, default=list)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_captions', to='dermatology.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dermatology_voice_captions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dermatology_voicecaption',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Share link expiry; null = never expires', null=True)),
                ('query_params', models.JSONField(default=dict)),
                ('query_summary', models.CharField(blank=True, max_length=500)),
                ('file_path', models.CharField(blank=True, max_length=1000)),
                ('file_size', models.BigIntegerField(default=0)),
                ('patient_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('share_mode', models.CharField(choices=[('private', 'Private'), ('authenticated', 'Any logged-in user'), ('public', 'Anyone with link')], default='private', max_length=20)),
                ('share_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('progress_message', models.CharField(blank=True, max_length=255)),
                ('progress_percent', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dermatology_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dermatology_export',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='dermatology_user_id_c7a4c1_idx'), models.Index(fields=['status', 'created_at'], name='dermatology_status_761030_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['project'], name='dermatology_project_eff3f1_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['parent'], name='dermatology_parent__71bf53_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['name'], name='dermatology_name_e3ae55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('project', 'name', 'parent')},
        ),
        migrations.AddIndex(
            model_name='folderaccess',
            index=models.Index(fields=['folder'], name='dermatology_folder__15324e_idx'),
        ),
        migrations.AddIndex(
            model_name='folderaccess',
            index=models.Index(fields=['user'], name='dermatology_user_id_9c4fee_idx'),
        ),
        migrations.AddIndex(
            model_name='folderaccess',
            index=models.Index(fields=['role'], name='dermatology_role_965925_idx'),
        ),
        migrations.AddIndex(
            model_name='folderaccess',
            index=models.Index(fields=['folder', 'role'], name='dermatology_folder__e8b3d0_idx'),
        ),
        migrations.AddIndex(
            model_name='folderaccess',
            index=models.Index(fields=['user', 'role'], name='dermatology_user_id_f340dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folderaccess',
            unique_together={('user', 'folder')},
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['patient', 'classifier'], name='dermatology_patient_78e955_idx'),
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['classifier'], name='dermatology_classif_0c65e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quadranttype',
            unique_together={('project', 'name')},
        ),
        migrations.AddIndex(
            model_name='quadrantclassificationmarker',
            index=models.Index(fields=['patient', 'file_registry_id'], name='dermatology_patient_72a5a7_idx'),
        ),
        migrations.AddIndex(
            model_name='quadrantclassificationmarker',
            index=models.Index(fields=['patient', 'quadrant_type'], name='dermatology_patient_e143aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='quadrantclassificationmarker',
            constraint=models.UniqueConstraint(fields=('patient', 'file_registry_id'), name='derma_unique_patient_quadrant_marker_photo'),
        ),
        migrations.AlterUniqueTogether(
            name='quadranttypeusercolor',
            unique_together={('quadrant_type', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='regiontype',
            unique_together={('project', 'name')},
        ),
        migrations.AddIndex(
            model_name='regionannotation',
            index=models.Index(fields=['patient', 'file_registry_id'], name='dermatology_patient_48d6e1_idx'),
        ),
        migrations.AddIndex(
            model_name='regionannotation',
            index=models.Index(fields=['patient', 'region_type'], name='dermatology_patient_7127bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='regiontypeusercolor',
            unique_together={('region_type', 'user')},
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['visibility'], name='dermatology_visibil_b27cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['uploaded_at'], name='dermatology_uploade_a1749c_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['folder'], name='dermatology_folder__0a8185_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['project'], name='dermatology_project_c7544a_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['name'], name='dermatology_name_7f9b18_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['visibility', 'uploaded_at'], name='dermatology_visibil_3cf7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecaption',
            index=models.Index(fields=['patient', 'processing_status'], name='dermatology_patient_8b99dd_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecaption',
            index=models.Index(fields=['processing_status'], name='dermatology_process_703693_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecaption',
            index=models.Index(fields=['user'], name='dermatology_user_id_feaee2_idx'),
        ),
    ]
