# Generated by Django 5.2.15 on 2026-09-13 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0006_drop_dicom_resource_fields'),
        ('brain', '0023_remove_folder_is_demo'),
        ('common', '0053_demo_guest_project_access'),
        ('dermatology', '0001_initial'),
        ('laparoscopy', '0015_remove_folder_is_demo'),
        ('maxillo', '0033_remove_folder_is_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationset',
            name='dermatology_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_sets', to='dermatology.patient'),
        ),
        migrations.AlterField(
            model_name='annotationset',
            name='domain',
            field=models.CharField(choices=[('maxillo', 'Maxillo'), ('brain', 'Brain'), ('laparoscopy', 'Laparoscopy'), ('dermatology', 'Dermatology')], default='maxillo', max_length=20),
        ),
        migrations.AddIndex(
            model_name='annotationset',
            index=models.Index(fields=['dermatology_patient', 'kind'], name='annotations_dermato_2090a1_idx'),
        ),
    ]
